Implement ThemePovider
DevExpress-Examples/devextreme-project-template-theme-selector pull request #1
Opened 2023-01-06 17:24 UTC by artem-kurchenko

- Changed ThemeService to a more React-generic solution
- Fixed warning about addListner

2023-01-10 13:05 UTC, dxArtemiusz approved these changes
Ok

2023-01-11 12:19 UTC, 16adianay approved these changes

2023-01-11 13:53 UTC, LexDX requested changes

2023-01-11 13:53 UTC, LexDX commented on react/src/contexts/theme.js
> +        refreshTheme();
I do not see the Swatch change. As this example is based on our Project Template, I think this is the must have feature.

2023-01-12 06:47 UTC, artem-kurchenko commented on react/src/contexts/theme.js
> +        refreshTheme();
It's a different task. Here I'm correcting React-related logic. See the original description

2023-01-12 06:48 UTC, merged

2023-01-12 10:30 UTC, LexDX commented on react/src/contexts/theme.js
> +        refreshTheme();
Ok. But we need to create such an example (i.e. improve the current one) in any way as this should cover a lot of common tasks.

2023-01-12 15:13 UTC, artem-kurchenko commented on react/src/contexts/theme.js
> +        refreshTheme();
yep thanks, it's in plans